# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-16.10"
  guestHostname = "development"
  config.vm.define guestHostname

  guestUsername = ""
  guestPassword = ""
  guestHome = ""

  hostUsername = ENV['USERNAME']
  hostHome = ENV['HOME']

  mountHome = "/mnt/home" 
  config.vm.synced_folder hostHome, mountHome

  provider = ""
  if ARGV[1] and (ARGV[1].split('=')[0] == "--provider" or ARGV[2])
    provider = (ARGV[1].split('=')[1] || ARGV[2])
  else
    provider = (ENV['VAGRANT_DEFAULT_PROVIDER'] || "virtualbox")
  end

  if Dir.glob("#{File.dirname(__FILE__)}/.vagrant/machines/" + guestHostname + "/*").empty? || ARGV[1] == '--provision'
    
    print "Username: "
    guestUsername = STDIN.gets.chomp

    print "Password: "
    guestPassword = STDIN.gets.chomp
    print "\n"

    guestHome = File.join("/home/", guestUsername)

  end  

  config.vm.provider "virtualbox" do |v|
    v.name = guestHostname
    v.memory = 8192
    v.cpus = 2
    v.customize ["modifyvm", :id, "--vram", "128"]
    v.gui = true
    provider = "virtualbox"
  end

  config.vm.provider "vmware_fusion" do |v|
    v.vmx['displayname'] = guestHostname
    v.vmx["memsize"] = "8192"
    v.vmx["numvcpus"] = "2"
    v.vmx["vramsize"] = "134217728"
    v.gui = true
    provider = "vmware_fusion"
  end   

  config.vm.provision "shell" do |s|
    s.path = "Bootstrap/Provision.sh"
    s.args   = [provider]
    s.binary = true
  end

  config.vm.provision "shell", inline: "adduser " + guestUsername + " --disabled-password --gecos \",,,\"" 
  config.vm.provision "shell", inline: "echo " + guestUsername + ":" + guestPassword + " | chpasswd"
  config.vm.provision "shell", inline: "adduser " + guestUsername + " sudo"
  config.vm.provision "shell", inline: "adduser " + guestUsername + " docker"

  config.vm.provision "shell", inline: "mkdir " + File.join(guestHome, ".ssh")
  config.vm.provision "shell", inline: "ln -s " + File.join(mountHome, ".ssh/*") + " " + File.join(guestHome, ".ssh")

  config.vm.provision "shell", inline: "mkdir " + File.join(guestHome, "Workspaces")
  config.vm.provision "shell", inline: "mkdir " + File.join(guestHome, "Workspaces/go")

  config.vm.provision "shell", path: "Login/Shell.sh"

  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # sed -i 's/# export PATH/export PATH/' /home/tysont/.zshrc
  # sed -i '1s/^/export GOPATH=$HOME\/Workspaces\/go\n/' /home/tysont/.zshrc
  # sed -i '1s/^/export GOROOT=\/opt\/go\n/' /home/tysont/.zshrc

end 